"""cria tabela de produtos favoritos do user

Revision ID: a6a2c7890fff
Revises: 6f7d9f3c0712
Create Date: 2025-10-30 23:11:29.543619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a2c7890fff'
down_revision: Union[str, Sequence[str], None] = '6f7d9f3c0712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_favorite_product_id'), 'user_favorite_product', ['id'], unique=False)
    op.create_index(op.f('ix_user_favorite_product_product_id'), 'user_favorite_product', ['product_id'], unique=True)
    op.create_index(op.f('ix_user_favorite_product_user_id'), 'user_favorite_product', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_favorite_product_user_id'), table_name='user_favorite_product')
    op.drop_index(op.f('ix_user_favorite_product_product_id'), table_name='user_favorite_product')
    op.drop_index(op.f('ix_user_favorite_product_id'), table_name='user_favorite_product')
    op.drop_table('user_favorite_product')
    # ### end Alembic commands ###
